### PR TITLE
Dxs_v3 VMs work fine with the existing templates

### PR DESCRIPTION
**Pull request by achamayou**
@johnkord as discussed previously, we've tried this out, and it works great. This is really helpful when testing, because we don't want to use SGX VMs for clients, and it's super convenient to have everything in one file, on the same vNet, rather than need to do bits and pieces in different ways.

I'm happy to be on the hook for any maintenance related to this of course.

### CODE REVIEW

**Comment by achamayou** [comment]
@johnkord any feedback on this? We find this really useful, not just for repeatable benchmark setup but also for our CI setup, which is a mix of SGX and non-SGX kit (for costs reasons).

oe-engine is such a nice way to define a box setup, we wish we could use it for everything ;)

**Comment by johnkord** [comment]
I like this idea, since oe-engine is an easy tool to use, and that this change is simply just allowing different values for VM sizes. Maybe we should "force" a vanilla deployment if the VM size isn't a DC series VM size? Technically, I'm not sure who the "maintainer" is for this repo right now, but I do know that @shruti25ratnam is actively working on it.

@shruti25ratnam what do you think about this change? Do you think there would be any maintenance costs in the future? Let's chat about this sometime soon!

By the way, @andschwa Do you think oe-engine should go into the openenclave organization? It's Azure specific, but I imagine it could be extended (probably high cost) to work with other cloud providers. I'm not sure if that matters for the openenclave org, does it?

**Comment by achamayou** [comment]
@johnkord orcing a vanilla deployment on non-SGX boxes sounds good, I'll have a look at adding that.

I'm conscious that this is an extension of the original scope for oe-engine, hence the offer to help with any associated maintenance increase this might cause :)

**Comment by andschwa** [comment]
> By the way, @andschwa Do you think oe-engine should go into the openenclave organization? It's Azure specific, but I imagine it could be extended (probably high cost) to work with other cloud providers. I'm not sure if that matters for the openenclave org, does it?

Absolutely not. It's Azure product, not Open Enclave project related.

**Comment by andschwa** [comment]
> By the way, @andschwa Do you think oe-engine should go into the openenclave organization? It's Azure specific, but I imagine it could be extended (probably high cost) to work with other cloud providers. I'm not sure if that matters for the openenclave org, does it?

Absolutely not. It's Azure product, not Open Enclave project related.

**Comment by achamayou** [comment]
@shruti25ratnam what do you think about this change? Is there anything I can improve?

**Comment by andschwa** [comment]
@johnkord @shruti25ratnam I am for this PR, we might as well do it!

**Comment by andschwa** [comment]
(Also I found it funny that this came from dcos-engine, which came from acs-engine, which was deprecated for aks-engine, in the words of our colleagues "this is just such a nice little tool for launching VMs," so we should consider having an "azure-engine" that does the VM deployment, and oe-engine that just adds the OE stuff like installing SGX etc.)

**Comment by achamayou** [comment]
@andschwa it'd definitely be excellent to have an azure-engine, with an oe plugin that would also install the SGX driver, PSW, OE and so on. In the meantime though, merging this would let us manage our mixed environments much more easily!

**Comment by shruti25ratnam** [comment]
Really sorry for the delayed update. Adding Dsv3 sizes should be fine for the existing templates. It's merely a design choice, so if everyone's ok with it we can go ahead. The changes look fine to me. 
@johnkord Yes, we can discuss the maintenance aspect.

**Comment by andschwa** [comment]
Cool, let’s do it!

**Comment by achamayou** [comment]
@shruti25ratnam thank you! Like I said, I'm happy to be on the hook for maintenance arising from this change.

**Comment by achamayou** [comment]
@shruti25ratnam could you merge the PR whenever convenient?

**Comment by johnkord** [comment]
Merging this, as @achamayou has been quite patient waiting for this change to go in! Thanks so much for your contribution @achamayou :)

**Comment by shruti25ratnam** [comment]
Thanks John and Amaury! for working on and merging the change, while I've been out of work this week :)

**Comment by andschwa** [comment]
Hope you're feeling better!

**Pull request merged**
