### PR TITLE
Skip sgx driver install if /dev/sgx is present

### PR DESCRIPTION
**Pull request by vtikoo**

### CODE REVIEW

**Comment by achamayou** [comment]
@vtikoo @paulcallen this is always the case on 18.04, since linux-azure now includes the sgx. One problem is that the version that ships through this package is potentially late on intel releases (1.22 right now, versus 1.32 from Intel), and unless that's kept more or less in sync with the PSW (libsgx-*), there may be some incompatibilities.

**Comment by paulcallen** [comment]
@achamayou  DC_v2 SKUs working with gen-2 ubuntu images should work fine with this change and should not install the driver. old DC v1 SKUs are being deprecated so I am not too worried about that, but we should make sure we have the latest driver. We are investigating the latest intel driver issue.

**Comment by vtikoo** [comment]
@Francis-Liu yes I intend to do so. The dummy commits are to trigger rebuilds, as I dont have permissions to rerun a build in Jenkins.

**Comment by Francis-Liu** [comment]
Ah ha! I see.

**Comment by BRMcLaren** [comment]
Hey @vtikoo , it looks like the CI is giving you some problems. Could you squash your commit into one and we will rerun it a few times? There is added stress to Cloud provided infrastracture due to the COVID Pandemic, but overall unsure what is happening.

**Comment by BRMcLaren** [comment]
https://oe-jenkins-tf.westeurope.cloudapp.azure.com/job/oe-engine/job/oe-engine-CI/job/PR-74/

7, 9, 10, 11, 12, 13

Are all builds related to this. If they all fail, this may not be CI related. If there is flakiness, an investigation is needed but we should proceed with merging this PR.

**Comment by BRMcLaren** [comment]
image


Odd. Seems it is passing now.

**Comment by achamayou** [comment]
@paulcallen yes, because since linux-azure - 5.0.0-1031.33 (https://bugs.launchpad.net/kernel-sru-workflow/+bug/1862239), they will have the driver pre-installed even when using isVanilla: true. On apt upgrade though, they may or may not get a driver upgrade, depending on what Canonical has put in their latest build of the linux-azure package.

That driver version may or may not be compatible with the currently installed Intel PSW. One is controlled by Canonical, the other by Intel, there's no dependency relationship defined between the two as far as apt is concerned. On apt upgrade, the latest PSW released by Intel will also get picked up. That may or may not work with the version of the driver Canonical ships with linux-azure at that time.

I'm sorry, this is only tangentially related to this PR, I'm just nervous about this situation. The change itself is fine.

**Pull request merged**
